name: Build and Release
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

permissions:
  contents: write
# Where will they run
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleDebug
      - name: Create Release
        run: |
          ARTIFACT_PATHNAME_APK=$(ls app/build/outputs/apk/debug/*.apk | head -n 1)
          echo ${ARTIFACT_PATHNAME_APK}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${ARTIFACT_PATHNAME_APK}
          name: Test-Release
