name: Build and Release
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
    tags:
      - '*'

# Where will they run
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"
      #- name: Setup Gradle
      #  uses: gradle/gradle-build-action@v2
      #  with:
        #  gradle-version: current
        #  arguments: assembleDebug
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
          name: Test-Release
